linters:
  enable:
    - govet
    - errcheck
    - revive
    - staticcheck

linters-settings:
  govet:
    enable-all: true
    disable:
      - fieldalignment
  revive:
    rules:
      - name: var-declaration
      - name: error-return